// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateCategoriesBatch implements pgx.CopyFromSource.
type iteratorForCreateCategoriesBatch struct {
	rows                 []CreateCategoriesBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCategoriesBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCategoriesBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForCreateCategoriesBatch) Err() error {
	return nil
}

func (q *Queries) CreateCategoriesBatch(ctx context.Context, arg []CreateCategoriesBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"categories"}, []string{"id", "name", "description"}, &iteratorForCreateCategoriesBatch{rows: arg})
}
