// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          string
	Name        string
	Description pgtype.Text
}

type Course struct {
	ID          string
	CategoryID  string
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
}
