// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateCategoriesBatchParams struct {
	ID          string
	Name        string
	Description pgtype.Text
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, description)
VALUES ($1, $2, $3)
RETURNING id, name, description
`

type CreateCategoryParams struct {
	ID          string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.ID, arg.Name, arg.Description)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
insert into courses (id, category_id, name, description, price)
values ($1,$2,$3,$4,$5)
RETURNING id, category_id, name, description, price
`

type CreateCourseParams struct {
	ID          string
	CategoryID  string
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, description
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description
FROM categories
ORDER BY
    -- Handle Ascending Cases
    CASE WHEN $1::text <> 'DESC' THEN
        CASE 
            WHEN $2::text = 'id' THEN id
            WHEN $2::text = 'name' THEN name
            WHEN $2::text = 'description' THEN description
        END
    END ASC,
    -- Handle Descending Cases
    CASE WHEN $1::text = 'DESC' THEN
        CASE 
            WHEN $2::text = 'id' THEN id
            WHEN $2::text = 'name' THEN name
            WHEN $2::text = 'description' THEN description
        END
    END DESC
LIMIT $4
OFFSET $3
`

type ListCategoriesParams struct {
	SortOrder  string
	SortColumn string
	OffsetVal  int32
	LimitVal   int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories,
		arg.SortOrder,
		arg.SortColumn,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, description = $3
WHERE id = $1
RETURNING id, name, description
`

type UpdateCategoryParams struct {
	ID          string
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Description)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
