package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/jb-oliveira/fullcycle/GRAPHQL/graph/model"
)

// Courses is the resolver for the courses field.
func (r *categoryResolver) Courses(ctx context.Context, obj *model.Category) ([]*model.Course, error) {
	courses, err := r.CourseDB.FindByCategoryID(obj.ID)
	if err != nil {
		return nil, err
	}
	var modelCourses []*model.Course
	for _, course := range courses {
		modelCourses = append(modelCourses, &model.Course{
			ID:          course.ID,
			Name:        course.Name,
			Description: &course.Description,
		})
	}
	return modelCourses, nil
}

// Category is the resolver for the category field.
func (r *courseResolver) Category(ctx context.Context, obj *model.Course) (*model.Category, error) {
	cat, err := r.CategoryDB.FindByCourseID(obj.ID)
	if err != nil {
		return nil, err
	}
	return &model.Category{
		ID:          cat.Id,
		Name:        cat.Name,
		Description: &cat.Description,
	}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategoryInput) (*model.Category, error) {
	r.CategoryDB.Name = input.Name
	if input.Description != nil {
		r.CategoryDB.Description = *input.Description
	}
	err := r.CategoryDB.Create()
	if err != nil {
		return nil, err
	}
	return &model.Category{
		ID:          r.CategoryDB.Id,
		Name:        r.CategoryDB.Name,
		Description: &r.CategoryDB.Description,
	}, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCourseInput) (*model.Course, error) {
	r.CourseDB.Name = input.Name
	if input.Description != nil {
		r.CourseDB.Description = *input.Description
	}
	r.CourseDB.CategoryID = input.CategoryID
	err := r.CourseDB.Create()
	if err != nil {
		return nil, err
	}
	return &model.Course{
		ID:          r.CourseDB.ID,
		Name:        r.CourseDB.Name,
		Description: &r.CourseDB.Description,
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	dbCategories, err := r.CategoryDB.FindAll()
	if err != nil {
		return nil, err
	}

	var categories []*model.Category
	for _, category := range dbCategories {
		categories = append(categories, &model.Category{
			ID:          category.Id,
			Name:        category.Name,
			Description: &category.Description,
		})
	}
	return categories, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	courses, err := r.CourseDB.FindAll()
	if err != nil {
		return nil, err
	}
	var modelCourses []*model.Course
	for _, course := range courses {
		modelCourses = append(modelCourses, &model.Course{
			ID:          course.ID,
			Name:        course.Name,
			Description: &course.Description,
		})
	}
	return modelCourses, nil
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Course returns CourseResolver implementation.
func (r *Resolver) Course() CourseResolver { return &courseResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type categoryResolver struct{ *Resolver }
type courseResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
