# FROM golang:1.25.6-alpine

# WORKDIR /app

# # copia todos os arquivos para o container
# COPY . . 
# # COPY go.mod go.sum ./

# RUN go build -ldflags="-w -s" -o server .

# EXPOSE 8080

# CMD ["./server"]


# Multi-stage build
# So builda o binario na primeira etapa
FROM golang:1.25.6-alpine AS builder
WORKDIR /app
COPY . . 
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o server .
EXPOSE 8080

# joga num imagem minima
FROM scratch
COPY --from=builder /app/server .
CMD ["./server"]