package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/jb-oliveira/fullcycle/CleanArch/internal/infra/graph/model"
	"github.com/jb-oliveira/fullcycle/CleanArch/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.OrderInput) (*model.OrderOutput, error) {
	dto := usecase.CreateOrderInput{
		ID:    input.ID,
		Price: input.Price,
		Tax:   input.Tax,
	}
	output, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}
	return &model.OrderOutput{
		ID:         output.ID,
		Price:      output.Price,
		Tax:        output.Tax,
		FinalPrice: output.FinalPrice,
	}, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, page int32, limit int32, sort string, sortDir string) ([]*model.OrderOutput, error) {
	newVar := int(page)
	newVar1 := int(limit)
	orders, err := r.ListOrdersUseCase.Execute(newVar, newVar1, sort, sortDir)
	if err != nil {
		return nil, err
	}
	var ordersOutput []*model.OrderOutput
	for _, order := range orders {
		ordersOutput = append(ordersOutput, &model.OrderOutput{
			ID:         order.ID,
			Price:      order.Price,
			Tax:        order.Tax,
			FinalPrice: order.CalculateFinalPrice(),
		})
	}
	return ordersOutput, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
