// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/jb-oliveira/fullcycle/DI/product"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func NewInsertProductUseCase(db *sql.DB) product.InsertProductUseCase {
	productRepository := product.NewProductRepositoryPostgres(db)
	insertProductUseCase := product.NewProductUseCaseImpl(productRepository)
	return insertProductUseCase
}

// wire.go:

var setRepositoryDependency = wire.NewSet(product.NewProductRepositoryPostgres, product.NewProductUseCaseImpl)
