// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/infra/grpc/protofiles/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax           float64                `protobuf:"fixed64,3,opt,name=tax,proto3" json:"tax,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_protofiles_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	SortDir       string                 `protobuf:"bytes,4,opt,name=sort_dir,json=sortDir,proto3" json:"sort_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_protofiles_order_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListOrdersRequest) GetSortDir() string {
	if x != nil {
		return x.SortDir
	}
	return ""
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_protofiles_order_proto_rawDescGZIP(), []int{2}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax           float64                `protobuf:"fixed64,3,opt,name=tax,proto3" json:"tax,omitempty"`
	FinalPrice    float64                `protobuf:"fixed64,4,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_protofiles_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_protofiles_order_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *Order) GetFinalPrice() float64 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

var File_internal_infra_grpc_protofiles_order_proto protoreflect.FileDescriptor

const file_internal_infra_grpc_protofiles_order_proto_rawDesc = "" +
	"\n" +
	"*internal/infra/grpc/protofiles/order.proto\x12\x02pb\"L\n" +
	"\x12CreateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x10\n" +
	"\x03tax\x18\x03 \x01(\x01R\x03tax\"l\n" +
	"\x11ListOrdersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x19\n" +
	"\bsort_dir\x18\x04 \x01(\tR\asortDir\"7\n" +
	"\x12ListOrdersResponse\x12!\n" +
	"\x06orders\x18\x01 \x03(\v2\t.pb.OrderR\x06orders\"`\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x10\n" +
	"\x03tax\x18\x03 \x01(\x01R\x03tax\x12\x1f\n" +
	"\vfinal_price\x18\x04 \x01(\x01R\n" +
	"finalPrice2}\n" +
	"\fOrderService\x120\n" +
	"\vCreateOrder\x12\x16.pb.CreateOrderRequest\x1a\t.pb.Order\x12;\n" +
	"\n" +
	"ListOrders\x12\x15.pb.ListOrdersRequest\x1a\x16.pb.ListOrdersResponseB\x18Z\x16internal/infra/grpc/pbb\x06proto3"

var (
	file_internal_infra_grpc_protofiles_order_proto_rawDescOnce sync.Once
	file_internal_infra_grpc_protofiles_order_proto_rawDescData []byte
)

func file_internal_infra_grpc_protofiles_order_proto_rawDescGZIP() []byte {
	file_internal_infra_grpc_protofiles_order_proto_rawDescOnce.Do(func() {
		file_internal_infra_grpc_protofiles_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_protofiles_order_proto_rawDesc), len(file_internal_infra_grpc_protofiles_order_proto_rawDesc)))
	})
	return file_internal_infra_grpc_protofiles_order_proto_rawDescData
}

var file_internal_infra_grpc_protofiles_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_infra_grpc_protofiles_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil), // 0: pb.CreateOrderRequest
	(*ListOrdersRequest)(nil),  // 1: pb.ListOrdersRequest
	(*ListOrdersResponse)(nil), // 2: pb.ListOrdersResponse
	(*Order)(nil),              // 3: pb.Order
}
var file_internal_infra_grpc_protofiles_order_proto_depIdxs = []int32{
	3, // 0: pb.ListOrdersResponse.orders:type_name -> pb.Order
	0, // 1: pb.OrderService.CreateOrder:input_type -> pb.CreateOrderRequest
	1, // 2: pb.OrderService.ListOrders:input_type -> pb.ListOrdersRequest
	3, // 3: pb.OrderService.CreateOrder:output_type -> pb.Order
	2, // 4: pb.OrderService.ListOrders:output_type -> pb.ListOrdersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infra_grpc_protofiles_order_proto_init() }
func file_internal_infra_grpc_protofiles_order_proto_init() {
	if File_internal_infra_grpc_protofiles_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_protofiles_order_proto_rawDesc), len(file_internal_infra_grpc_protofiles_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_grpc_protofiles_order_proto_goTypes,
		DependencyIndexes: file_internal_infra_grpc_protofiles_order_proto_depIdxs,
		MessageInfos:      file_internal_infra_grpc_protofiles_order_proto_msgTypes,
	}.Build()
	File_internal_infra_grpc_protofiles_order_proto = out.File
	file_internal_infra_grpc_protofiles_order_proto_goTypes = nil
	file_internal_infra_grpc_protofiles_order_proto_depIdxs = nil
}
