#!/bin/bash

# Check the documentation at https://github.com/swaggo/swag?tab=readme-ov-file#getting-started
# To generate the project documentation

# Initialization
# swag init --parseDependency --dir ./ --output ./docs # generated by kiro
swag init -g cmd/server/main.go # course