// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :exec
insert into categories (id, name, description) values ($1, $2, $3)
`

type CreateCategoryParams struct {
	ID          string
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory, arg.ID, arg.Name, arg.Description)
	return err
}

const createCourse = `-- name: CreateCourse :exec
insert into courses (id, category_id, name, description, price) 
values ($1, $2, $3, $4, $5)
`

type CreateCourseParams struct {
	ID          string
	CategoryID  string
	Name        string
	Description sql.NullString
	Price       string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.ExecContext(ctx, createCourse,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	return err
}

const findCategoryByID = `-- name: FindCategoryByID :one
select id, name, description from categories where id = $1
`

func (q *Queries) FindCategoryByID(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, findCategoryByID, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const findCourseByID = `-- name: FindCourseByID :one
select id, category_id, name, description, price from courses where id = $1
`

func (q *Queries) FindCourseByID(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRowContext(ctx, findCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
	)
	return i, err
}
